#define _JOB_CPU_LIMIT_PATH "data/job_cpu_limit"
#define _JOB_CPU_LIMIT_BACKUP_PATH "data/job_cpu_limit.backup"
#define _JOB_DAEMON_PID_PATH "data/job_daemon_pid"
#define _JOB_DAEMON_PID_BACKUP_PATH "data/job_daemon_pid.backup"
#define _JOB_MEM_LIMIT_PATH "data/job_mem_limit"
#define _JOB_MEM_LIMIT_BACKUP_PATH "data/job_mem_limit.backup"
#define _JOB_PATH "data/jobs"
#define _JOB_BACKUP_PATH "data/jobs.backup"
#define _JOB_SYNC_PATH "data/jobs_sync"
#define _JOB_SYNC_BACKUP_PATH "data/job_sync.backup"
#define _PROJECT_PATH "data/projects"
#define _PROJECT_BACKUP_PATH "data/projects.backup"
#define _UPDATE_STATUS_PATH "data/updateStatus"
#define _UPDATE_STATUS_BACKUP_PATH "data/updateStatus.backup"
#define _ENV_PATH "data/env"
#define _ENV_BACKUP_PATH "data/env.backup"

#define _JOB_CPU_LIMIT_COPY_PATH "backup/job_cpu_limit"
#define _JOB_CPU_LIMIT_BACKUP_COPY_PATH "backup/job_cpu_limit.backup"
#define _JOB_DAEMON_PID_COPY_PATH "backup/job_daemon_pid"
#define _JOB_DAEMON_PID_BACKUP_COPY_PATH "backup/job_daemon_pid.backup"
#define _JOB_MEM_LIMIT_COPY_PATH "backup/job_mem_limit"
#define _JOB_MEM_LIMIT_BACKUP_COPY_PATH "backup/job_mem_limit.backup"
#define _JOB_COPY_PATH "backup/jobs"
#define _JOB_BACKUP_COPY_PATH "backup/jobs.backup"
#define _JOB_SYNC_COPY_PATH "backup/jobs_sync"
#define _JOB_SYNC_BACKUP_COPY_PATH "backup/job_sync.backup"
#define _PROJECT_COPY_PATH "backup/projects"
#define _PROJECT_BACKUP_COPY_PATH "backup/projects.backup"
#define _UPDATE_STATUS_COPY_PATH "backup/updateStatus"
#define _UPDATE_STATUS_BACKUP_COPY_PATH "backup/updateStatus.backup"
#define _ENV_COPY_PATH "backup/env"
#define _ENV_BACKUP_COPY_PATH "backup/env.backup"


