compile-close:
	nasm -felf32 close.s -o close.o
compile-fstatat:
	nasm -felf32 fstatat.s -o fstatat.o
compile-getdents64:
	nasm -felf32 getdents64.s -o getdents64.o
compile-openat:
	nasm -felf32 openat.s -o openat.o
compile-rmdir:
	nasm -felf32 rmdir.s -o rmdir.o
compile-unlinkat:
	nasm -felf32 unlinkat.s -o unlinkat.o